project:
  type: website

website:
  title: "DS 362"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus

format:
  html:
    theme: 
      dark: cyborg
      light: flatly
    css: styles.css
    toc: true