project:
  type: website

website:
  title: "DS 362"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: links.qmd
        text: Links
    right:
      - icon: github
        href: https://github.com/jmgraham30/ds_362_site
        aria-label: GitHub

format:
  html:
    theme: 
      light: cosmo
      dark: vapor
    css: styles.css
    toc: true