---
title: "DS 362: Data-Driven Knowledge Discovery"
---

## Welcome!

Welcome to the course website for DS 362: Data-Driven Knowledge Discovery for Fall 2023.

This course is offered at the [University of Scranton](https://www.scranton.edu/) and is being taught by [Jason M. Graham](https://sites.google.com/site/jasonmgrahamus/) ([Mathematics Department](https://www.scranton.edu/academics/cas/math/index.shtml)) during the Fall 2023 semester.




## License

This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/).

This is a human-readable summary of (and not a substitute for) the license. Please see [https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode) for the full legal text.

You are free to:

* Share — copy and redistribute the material in any medium or format

* Adapt — remix, transform, and build upon the material

The licensor cannot revoke these freedoms as long as you follow the license terms.

* Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

* NonCommercial — You may not use the material for commercial purposes.

* ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

* No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

Notices:

You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation.

No warranties are given. The license may not give you all of the permissions necessary for your intended use. For example, other rights such as publicity, privacy, or moral rights may limit how you use the material.